package cli

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"io"

	mimicapply "mimic/internal/apply"
	mimicmongo "mimic/internal/mongo"
	"mimic/internal/plan"
)

func runApply(ctx context.Context, args []string, stdout io.Writer) error {
	fs := flag.NewFlagSet("apply", flag.ContinueOnError)
	fs.SetOutput(io.Discard)
	planPath := fs.String("plan", "", "plan file path")
	backupPath := fs.String("backup", "", "backup directory path")
	confirm := fs.String("confirm", "", "confirmation target name")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if err := requireFlagValue("plan", *planPath); err != nil {
		return err
	}
	if err := requireFlagValue("backup", *backupPath); err != nil {
		return err
	}
	if err := requireFlagValue("confirm", *confirm); err != nil {
		return err
	}
	approved, err := plan.ReadApprovedFile(*planPath)
	if err != nil {
		return err
	}
	if approved.Kind != "mimic.approvedPlan" {
		return errors.New("apply only accepts approved plans generated by mimic approve")
	}
	expectedChecksum := approved.ApprovedChecksum
	approved.ApprovedChecksum = ""
	actualChecksum, err := plan.ChecksumValue(approved)
	if err != nil {
		return err
	}
	if expectedChecksum == "" || expectedChecksum != actualChecksum {
		return errors.New("approved plan checksum is invalid")
	}
	approved.ApprovedChecksum = expectedChecksum
	backup, err := mimicmongo.ReadBackupMetadata(*backupPath)
	if err != nil {
		return err
	}
	if backup.ApprovedPlanChecksum != approved.ApprovedChecksum {
		return errors.New("backup metadata does not match approved plan checksum")
	}
	if *confirm != approved.Target {
		return fmt.Errorf("confirmation must match target %q", approved.Target)
	}
	if err := mimicapply.ApprovedPlan(ctx, approved); err != nil {
		return err
	}
	fmt.Fprintf(stdout, "applied approved plan to target: %s\n", approved.Target)
	fmt.Fprintf(stdout, "operations: %d\n", len(approved.ApprovedOperations))
	return nil
}
